# These are supported funding model platforms

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://splunkable.com', 'https://www.linkedin.com/company/splunkable', 'https://www.youtube.com/@splunkable']
